blank_issues_enabled: true
contact_links:
  - name: README & Documentation
    url: https://github.com/lifedraft/targetprocess-cli#readme
    about: Check the README for usage instructions and examples.
